spring.application.name=Endangered Animals
spring.datasource.url=jdbc:postgresql://localhost:5432/endangered_animals
spring.datasource.username=USER
spring.datasource.password=PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=none
